FROM jenkins/jenkins:2.440.3-jdk11


USER jenkins
RUN jenkins-plugin-cli --plugins blueocean:1.27.16 build-timestamp:1.0.3 timestamper:1.17 pollscm:1.3.1 github-api:1.321-468.v6a_9f5f2d5a_7e
USER root
ENV FLUENTD_HOST "fluentd"
ENV FLUENTD_PORT "24224"
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV JENKINS_URL "http://jenkins:10000"
ENV ACCESS_KEY ${ACCESS_KEY}
ENV SECRET_KEY ${SECRET_KEY}

COPY ./requirements.txt requirements.txt
RUN apt update && \
    apt install -y python3 python3-venv python3-pip

# Criar e ativar o ambiente virtual
RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"
RUN python3 --version
# Instalar as dependências no ambiente virtual
RUN pip3 install -r requirements.txt
RUN pip3 list

COPY jenkins/1-configureJenkins.groovy /usr/share/jenkins/ref/init.groovy.d/1-configureJenkins.groovy
COPY jenkins/2-addAccessKeys.groovy /usr/share/jenkins/ref/init.groovy.d/2-addAccessKeys.groovy
